// examples/edgio-vue2-example/src/components/Header.vue
<template>
  <div class="flex flex-row flex-wrap items-center justify-between py-3 px-5">
    <router-link to="/">
      <img src="/logo/white.svg" class="h-[25px] w-[60.2px] bg-white/5" />
    </router-link>
    <div class="flex flex-row items-center space-x-4 py-1">
      <router-link to="/about">
        <span class="text-[#FFFFFF75]">About</span>
      </router-link>
      <router-link to="/commerce">
        <span class="text-[#FFFFFF75]">Commerce</span>
      </router-link>
      <a href="https://github.com/layer0-docs/layer0-vue2-example" target="_blank">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" class="fill-[#FFFFFF75]" viewBox="0 0 16 16">
          <path
            d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"
          />
        </svg>
      </a>
    </div>
  </div>
</template>

// examples/edgio-svelte-example/src/components/Header.svelte
<script>
  import { getCategories } from '../lib/cms'
  import { Prefetch } from '@layer0/svelte'
  const fetchCategories = (async () => {
    const response = await getCategories()
    return await response.categories
  })()
  import { Link } from 'svelte-navigator'
</script>

<header class="bg-white pt-2 flex flex-col items-center">
  <Link to="/">
    <img width={200} height={55.59} src="/layer0-icon.svg" alt="Layer0 Logo" title="Layer0 Logo" />
    <div class="text-center text-gray-700">Svelte Example</div>
  </Link>
  <div class="flex flex-col items-center w-full border-b-[1px] border-[#eaeaea]">
    <div class="py-4 w-2/3 flex flex-row justify-between">
      {#await fetchCategories}
        {''}
      {:then data}
        {#each data as category}
          <Link to={category.href}>
            <Prefetch url={`/api${category.href}`} immediately>
              {category.categoryName}
            </Prefetch>
          </Link>
        {/each}
      {:catch error}
        {''}
      {/await}
    </div>
  </div>
</header>
