// examples/edgio-astro-ssr-example/src/components/Product.jsx
import React from 'react'
import { relativizeURL } from '@/helper'
import { StarIcon } from '@heroicons/react/solid/esm/index.js'
import { HeartIcon, StarIcon as StarIconOutline } from '@heroicons/react/outline/esm/index.js'

const Product = ({ data }) => {
  return (
    <div className="flex w-full flex-col items-center">
      <div className="pb-12 flex max-w-6xl flex-col lg:flex-row">
        <div className="relative flex w-full flex-col items-start lg:w-1/2">
          <div className="absolute top-0 left-0 z-10 flex flex-col items-start">
            <h3 className="border border-gray-200 bg-white py-2 px-4 text-2xl font-bold text-black">{data.name}</h3>
            <h4 className="border border-gray-200 bg-white py-2 px-4 text-lg text-black">{`$ ${data.prices.price.value} ${data.prices.price.currencyCode}`}</h4>
          </div>
          <HeartIcon className="absolute top-0 right-0 z-10 h-[50px] w-[50px] border border-gray-200 bg-white p-2" />
          <div className="flex w-full flex-col items-center">
            <img src={relativizeURL(data.images[0].url)} className="h-auto w-full max-w-[600px]" />
          </div>
          <div className="product-thumbnails mt-5 flex flex-row items-start gap-x-2 overflow-x-scroll">
            {data.images.map((i, ind) => (
              <img key={i.url} loading="lazy" src={relativizeURL(i.url)} className="h-[250px] w-auto hover:bg-white" />
            ))}
          </div>
        </div>
        <div className="flex w-full flex-col items-start px-10 lg:w-1/2">
          <h1 className="mt-10 text-3xl font-bold text-white lg:mt-0">{data.name}</h1>
          <h2 dangerouslySetInnerHTML={{ __html: data.description }} className="text-md mt-5 font-light text-[#FFFFFF75]"></h2>
          <div className="mt-10 flex w-full flex-row justify-between">
            <div className="flex flex-row items-center space-x-1">
              <StarIcon className="h-[20px] w-[20px] text-[#FFFFFF75]" />
              <StarIcon className="h-[20px] w-[20px] text-[#FFFFFF75]" />
              <StarIcon className="h-[20px] w-[20px] text-[#FFFFFF75]" />
              <StarIcon className="h-[20px] w-[20px] text-[#FFFFFF75]" />
              <StarIconOutline className="h-[18px] w-[18px] text-[#FFFFFF75]" />
            </div>
            <span className="text-[#FFFFFF75]">36 reviews</span>
          </div>
          <button className="mt-5 w-full bg-black px-2 py-4 uppercase text-white">Add To Cart</button>
          <span className="mt-5 text-lg font-medium text-white">Care</span>
          <span className="mt-2 font-light text-[#FFFFFF75]">This is a limited edition production run. Printing starts when the drop ends.</span>
          <div className="mt-5 h-[1px] w-full bg-[#FFFFFF30]"></div>
          <span className="mt-5 text-lg font-medium text-white">Details</span>
          <span className="mt-2 font-light text-[#FFFFFF75]">
            This is a limited edition production run. Printing starts when the drop ends. Reminder: Bad Boys For Life. Shipping may take 10+ days due
            to COVID-19.
          </span>
          <div className="mt-5 h-[1px] w-full bg-[#FFFFFF30]"></div>
        </div>
      </div>
    </div>
  )
}

export default Product

// examples/edgio-angular-example/src/app/product/product.component.ts
import { HttpClient } from '@angular/common/http'
import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css'],
})
export class ProductComponent implements OnInit {
  data: any = null

  constructor(route: ActivatedRoute, private http: HttpClient) {
    route.url.subscribe(async (i) => {
      if (i[1].path) {
        this.data = await this.http
          .get(`https://layer0-docs-layer0-ecommmerce-api-example-default.layer0-limelight.link/products/${i[1].path}`)
          .toPromise()
      }
    })
  }

  ngOnInit(): void {}
}

<div class="flex w-full flex-col items-center">
  <div class="pb-12 flex max-w-6xl flex-col lg:flex-row">
    <div class="relative flex w-full flex-col items-start lg:w-1/2">
      <div class="absolute top-0 left-0 z-10 flex flex-col items-start">
        <h3 class="border border-gray-200 bg-white py-2 px-4 text-2xl font-bold text-black">{{ data?.name }}</h3>
        <h4 class="border border-gray-200 bg-white py-2 px-4 text-lg text-black">
          {{ data?.prices?.price?.value }}{{ data?.prices?.price?.currencyCode }}
        </h4>
      </div>
      <!-- <HeartIcon class="absolute top-0 right-0 z-10 h-[50px] w-[50px] border border-gray-200 bg-white p-2" /> -->
      <div *ngIf="data?.images" class="flex w-full flex-col items-center">
        <img [src]="data?.images[0]?.url" class="h-auto w-full max-w-[600px]" />
      </div>
      <div *ngIf="data?.images?.length" class="product-thumbnails mt-5 flex flex-row items-start gap-x-2 overflow-x-scroll">
        <img *ngFor="let image of data?.images" loading="lazy" [src]="image?.url" class="h-[250px] w-auto hover:bg-white" />
      </div>
    </div>
    <div class="flex w-full flex-col items-start px-10 lg:w-1/2">
      <h1 class="mt-10 text-3xl font-bold text-white lg:mt-0">{{ data?.name }}</h1>
      <div *ngIf="data?.description" [innerHTML]="data?.description" class="text-md mt-5 font-light text-[#FFFFFF75]"></div>
      <div class="mt-10 flex w-full flex-row justify-between">
        <div class="flex flex-row items-center space-x-1">
          <!-- <StarIcon class="h-[20px] w-[20px] text-[#FFFFFF75]" />
          <StarIcon class="h-[20px] w-[20px] text-[#FFFFFF75]" />
          <StarIcon class="h-[20px] w-[20px] text-[#FFFFFF75]" />
          <StarIcon class="h-[20px] w-[20px] text-[#FFFFFF75]" />
          <StarIconOutline class="h-[18px] w-[18px] text-[#FFFFFF75]" /> -->
        </div>
        <span class="text-[#FFFFFF75]">36 reviews</span>
      </div>
      <button class="mt-5 w-full bg-black px-2 py-4 uppercase text-white">Add To Cart</button>
      <span class="mt-5 text-lg font-medium text-white">Care</span>
      <span class="mt-2 font-light text-[#FFFFFF75]">This is a limited edition production run. Printing starts when the drop ends.</span>
      <div class="mt-5 h-[1px] w-full bg-[#FFFFFF30]"></div>
      <span class="mt-5 text-lg font-medium text-white">Details</span>
      <span class="mt-2 font-light text-[#FFFFFF75]">
        This is a limited edition production run. Printing starts when the drop ends. Reminder: Bad Boys For Life. Shipping may take 10+ days due to
        COVID-19.
      </span>
      <div class="mt-5 h-[1px] w-full bg-[#FFFFFF30]"></div>
    </div>
  </div>
</div>
