// examples/edgio-nuxt3-example/pages/commerce.vue
<template>
  <div class="flex-col items-center justify-start">
    <div class="flex w-full flex-row items-start px-5">
      <div class="pt-5 flex flex-col min-w-[200px]">
        <Sidebar />
      </div>
      <div class="flex flex-col items-start pt-5">
        <h2 class="text-[#FFFFFF75]">Showing {{ finalProducts ? finalProducts.length : '...' }} Results</h2>
        <div class="mt-5 grid grid-cols-1 sm:gird-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6">
          <NuxtLink :key="item.path" :to="`/product/${item.slug}`" v-for="item in finalProducts" class="relative mt-2 border border-white p-1">
            <ClientOnly>
              <prefetch :url="`/l0-api/products/${item.slug}`"><span class="h-0 w-0"></span></prefetch>
            </ClientOnly>
            <div class="absolute top-0 left-0 z-10 flex flex-col items-start">
              <h3 class="border border-gray-200 bg-white py-1 px-2 text-xs md:py-2 md:px-4 md:text-xl font-medium text-black">
                {{ item ? item.name : '' }}
              </h3>
              <h4 class="border border-gray-200 bg-white py-1 px-2 text-xs md:py-2 md:px-4 md:text-lg text-black">
                {{ item && item.prices ? item.prices.price.value : '' }}{{ item && item.prices ? item.prices.price.currencyCode : '' }}
              </h4>
            </div>
            <img
              width="1200"
              height="1200"
              loading="lazy"
              v-if="item.images"
              :src="relativizeURL(item.images[0].url)"
              class="h-full object-contain bg-white"
            />
            <div v-if="!item.images" class="h-full w-full bg-white/50 animate-pulse min-h-[100px] min-w-[100px]"></div>
          </NuxtLink>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { relativizeURL, getOrigin, filterProducts } from '@/lib/helper'

const route = useRoute()
const router = useRouter()

const hostHeader = useRequestHeaders(['host'])
const origin = getOrigin({ headers: { host: hostHeader.host } })

const fetchURL = (route) => {
  return `${origin}/l0-api/${route.params.name ? `categories/${route.params.name}` : 'products/all'}`
}

const { data } = await useFetch(fetchURL(route))

const finalProducts = useState('finalProducts', () => {
  return filterProducts(route.params.name ? data.value['items'] : data.value, route.query.filter)
})

const createFilter = async () => {
  if (!route.path.includes('/commerce')) return
  if (!route.query || (!route.query['filter'] && route.path.includes('commerce'))) {
    router.push({ path: route.path, query: { filter: 'trending' } })
  }
  const resp = await fetch(fetchURL(route))
  if (resp.ok) {
    const data = await resp.json()
    finalProducts.value = filterProducts(route.params.name ? data['items'] : data, route.query.filter)
  }
}

onMounted(() => {
  createFilter()
  watch(() => route.query, createFilter)
})
</script>

// examples/remix-express/app/routes/commerce.jsx
import { useEffect } from 'react'
import { json } from '@remix-run/node'
import Sidebar from '@/components/Sidebar'
import { filterProducts, getOrigin } from '@/helper'
import ProductPreview from '@/components/ProductPreview'
import { Outlet, useFetcher, useLoaderData, useParams } from '@remix-run/react'

export async function action({}) {
  return null
}

export const loader = async ({ request, params }) => {
  const host = request.headers.get('host')
  const origin = getOrigin({ headers: { host } })
  const url = new URL(request.url)
  const pathname = url.pathname
  const filter = url.searchParams.get('filter')
  const resp = await fetch(`${origin}/l0-api/${params.name ? `categories/${params.name}` : 'products/all'}`)
  let products = await resp.json()
  if (params.name) {
    products = products['items']
  }
  return json({ products, filter, pathname })
}

const Commerce = ({}) => {
  const { name } = useParams()
  const data = useLoaderData()
  const fetcher = useFetcher()
  useEffect(() => {
    if (name) {
      fetcher.submit(`/commerce/${name}`, { method: 'post' })
    } else {
      fetcher.submit(`/commerce`, { method: 'post' })
    }
  }, [name])
  return (
    <div className="flex-col items-center justify-start">
      <div className="flex w-full flex-row items-start px-5">
        <div className="flex min-w-[200px] flex-col pt-5">
          <Sidebar filter={data.filter} pathname={data.pathname} />
        </div>
        <div className="flex flex-col items-start pt-5">
          <h2 className="text-[#FFFFFF75]">Showing {data.products.length} Results</h2>
          <div className="sm:grid-cols-2 mt-5 grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6">
            {filterProducts(data.products, data.filter).map((i) => (
              <ProductPreview key={i.path} {...i} />
            ))}
          </div>
        </div>
      </div>
      <Outlet />
    </div>
  )
}

export default Commerce
