// examples/edgio-astro-example/src/components/Sidebar.jsx
import classNames from 'classnames'
import React, { useEffect, useState } from 'react'

const relevanceItems = [
  {
    name: 'Trending',
    filter: 'trending',
  },
  {
    name: 'Price: Low to High',
    filter: 'price-low-to-high',
  },
  {
    name: 'Price: High to Low',
    filter: 'price-high-to-low',
  },
]

const Sidebar = () => {
  const [filter, setFilter] = useState(undefined)
  const [listingItems, setListingItems] = useState([])
  const [pathWithoutQuery, setPathWithoutQuery] = useState(undefined)
  useEffect(() => {
    setPathWithoutQuery(window.location.pathname)
    setFilter(new URLSearchParams(window.location.search).get('filter'))
    fetch('/l0-api/categories/all')
      .then((res) => res.json())
      .then((res) => {
        setListingItems(res)
      })
  }, [])
  return (
    <div className="flex w-full flex-col">
      <h2 className="text-md font-light text-[#FFFFFF75]">Relevance</h2>
      {relevanceItems.map((item) => (
        <a
          key={item.name}
          className={classNames(
            'text-md mt-2 cursor-pointer',
            { 'font-light text-[#FFFFFF75]': filter !== item.filter },
            { 'font-medium text-[#FFFFFF]': filter === item.filter }
          )}
          onClick={(e) => {
            e.preventDefault()
            if (typeof window !== undefined) {
              const url = new URL(window.location)
              url.searchParams.set('filter', item.filter)
              window.location.href = url
            }
          }}
        >
          {item.name}
        </a>
      ))}
      <a
        href={`/commerce`}
        className={classNames(
          'text-md mt-7',
          { 'font-light text-[#FFFFFF75]': pathWithoutQuery !== `/commerce` },
          { 'font-medium text-[#FFFFFF]': pathWithoutQuery === `/commerce` }
        )}
      >
        Shop All
      </a>
      {listingItems.map((item) => (
        <a
          href={`/commerce/${item.slug}`}
          className={classNames(
            'text-md mt-2',
            { 'font-light text-[#FFFFFF75]': pathWithoutQuery !== `/commerce/${item.slug}` },
            { 'font-medium text-[#FFFFFF]': pathWithoutQuery === `/commerce/${item.slug}` }
          )}
        >
          {item.name}
        </a>
      ))}
    </div>
  )
}

export default Sidebar

// examples/edgio-saber-example/components/Sidebar.vue
<template>
  <div class="flex w-full flex-col">
    <h2 class="font-light text-[#FFFFFF75] text-md">Relevance</h2>
    <a
      :key="item.filter"
      v-for="item in relevance"
      @click="pushFilter(item.filter)"
      class="text-md mt-2 cursor-pointer"
      :class="{
        'font-medium text-[#FFFFFF]': $route.query.filter === item.filter,
        'font-light text-[#FFFFFF75]': $route.query.filter !== item.filter,
      }"
    >
      {{ item.name }}
    </a>
    <a
      href="/commerce.html"
      class="text-md mt-7"
      :class="{ 'font-medium text-[#FFFFFF]': $route.path === '/commerce', 'font-light text-[#FFFFFF75]': $route.path !== '/commerce' }"
    >
      Shop All
    </a>
    <a
      :key="item.slug"
      class="text-md mt-2"
      v-for="item in listingItems"
      :href="`/commerce/${item.slug}.html`"
      :class="{
        'font-medium text-[#FFFFFF]': $route.path === `/commerce/${item.slug}`,
        'font-light text-[#FFFFFF75]': $route.path !== `/commerce/${item.slug}`,
      }"
    >
      {{ item.name }}
    </a>
    <a
      :key="index"
      href="/commerce"
      v-for="(item, index) in fallbackListingItems"
      class="mt-2 text-md px-10 animate-pulse bg-white/50 py-1.5 w-[10px]"
    ></a>
  </div>
</template>

<script>
export default {
  name: 'Sidebar',
  methods: {
    pushFilter(filter) {
      this.$router.push({ path: this.$route.path, query: { filter } })
    },
  },
  data() {
    return {
      relevance: [
        {
          name: 'Trending',
          filter: 'trending',
        },
        {
          name: 'Price: Low to High',
          filter: 'price-low-to-high',
        },
        {
          name: 'Price: High to Low',
          filter: 'price-high-to-low',
        },
      ],
      listingItems: [],
      fallbackListingItems: new Array(9).fill(0),
    }
  },
  async mounted() {
    let resp = await fetch('/l0-api/categories/all')
    if (resp.ok) {
      let data = await resp.json()
      this.listingItems = data
      this.fallbackListingItems = []
    }
  },
}
</script>
